@startuml

title "Use Case - Create Project"

-> ":Controller": createProject(String, String, LocalDateTime)
activate ":Controller"

":Controller" -> ":ProjectManager" : createProject(String, String, LocalDateTime, LocalDateTime, User)
activate ":ProjectManager"

"

@enduml
