@startuml

title __BACKEND's Class Diagram__\n

  package taskman {
    package taskman.backend {
      class Controller {
          + Controller()
          + getTime()
          + updateTime()
          + getCurrentUser()
          + getUsers()
          + getUserTypes()
          + createUser()
          + removeUser()
          + login()
          + logout()
          + getProjects()
          + getProjectStatus()
          + createProject()
          + getTasks()
          + createTask()
          + getStartingsTimes()
          + initializePlan()
          + getPlannedResources()
          + getAlternativeResources()
          + changeResource()
          + cancelPlan()
          + getResourceTypes()
          + createResourceType()
          + createConstraint()
          + createResource()
          + addAlternativeToTask()
          + addDependencyToTask()
          + addRequirementToTask()
          + endTaskExecution()
          + makeExecuting()
          + exportSystem()
          + importSystem()
          + startSimulation()
          + cancelSimulation()
          + executeSimulation()
          - setClock()
          - setUserManager()
          - setProjectOrganizer()
          - setResourceManager()
      }
    }
  }
  

  Controller o-- Clock : clock
  Controller o-- UserManager : userManager
  Controller o-- ProjectOrganizer : projectOrganizer
  Controller o-- ResourceManager : resourceManager
  Controller o-- SimulationManager : simulationManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
