@startuml

title __IMPORTEXPORT's Class Diagram__\n

  package taskman {
    package taskman.backend {
      package taskman.backend.importexport {
        class ImportExportException {
            + ImportExportException()
        }
      }
    }
  }
  

  class WrappedPrintWriter {
      - printWriter : PrintWriter
      ~ WrappedPrintWriter()
      ~ lock()
      ~ println()
  }
  

  class WrappedPrintStream {
      - printStream : PrintStream
      ~ WrappedPrintStream()
      ~ lock()
      ~ println()
  }
  

  abstract class PrintStreamOrWriter {
      - PrintStreamOrWriter()
      {abstract} ~ lock()
      {abstract} ~ println()
  }
  

  class SentinelHolder {
      {static} + STACK_TRACE_ELEMENT_SENTINEL : StackTraceElement
      {static} + STACK_TRACE_SENTINEL : StackTraceElement[]
      - SentinelHolder()
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.importexport {
        class XmlObject {
            - xstream : XStream
            + XmlObject()
            + getResourceManager()
            + getUserManager()
            + getProjectOrganizer()
            + getClock()
            {static} - createXstream()
            + toXMLString()
            {static} + fromXMLString()
            + saveToFile()
            {static} + restoreFromFile()
        }
      }
    }
  }
  

  ImportExportException +-down- WrappedPrintWriter
  ImportExportException +-down- WrappedPrintStream
  ImportExportException +-down- PrintStreamOrWriter
  ImportExportException +-down- SentinelHolder
  XmlObject o-- ResourceManager : resourceManager
  XmlObject o-- UserManager : userManager
  XmlObject o-- ProjectOrganizer : projectOrganizer
  XmlObject o-- Clock : clock


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
