@startuml

title __TEST's Class Diagram__\n

  package test {
    class ClockTest {
        + beforeTest()
        + afterTest()
        + getSystemTime()
        + getSystemTimeExternalAdjustment()
        + updateSystemTime()
        + updateSystemTimeToMinimal()
        + updateSystemTimeToPast()
    }
  }
  

  package test {
    class ControllerTest {
        {static} - controller : Controller
        + runBeforeMethod()
        + runAfterMethod()
        + constructor()
        + project_and_task()
        + system_time()
        + user()
        - deleteFile()
        + import_export()
    }
  }
  

  package test {
    class DeveloperTest {
        + setUp()
        + testDeveloper_legal()
        + testDeveloper_illegalName()
        + testDeveloper_illegalPassword()
    }
  }
  

  package test {
    class ProjectManagerTest {
        + setUp()
        + testProjectManager()
        + testProjectManagerName()
        + testProjectManagerPassword()
    }
  }
  

  package test {
    class ProjectTest {
        - creation : LocalDateTime
        - due : LocalDateTime
        + setUp()
        + testProjectcorrect()
        + testProjectEarlyEndDate()
        + testProjectNoName()
        + testProjectIllegalUser()
        + testAddTask_legal()
        + testAddTask_illegalUser()
        + testIllegalIndexGetTask()
        + testRemoveTask()
        + testGetStatusFinished()
        + testGetStatusFailed()
    }
  }
  

  package test {
    class TaskTest {
        {static} - root : Task
        {static} - alternative1_3 : Task
        {static} - alternative1_2_1 : Task
        {static} - dependency1_2 : Task
        {static} - dependency1_1_3 : Task
        {static} - alternative1_3d : Task
        {static} + setUp()
        + testTask()
        + testIsFinished()
        + testIsAvailable()
        + testIllegalStateIsAvailable()
        + testDelay()
        + testIlegalStateDelay()
        + testUpdateStatus()
        + testInvalidEndTimeUpdateStatus()
        + testInvalidStatusUpdateStatus()
        + testAlternative()
        + testInvaladSetAlternative()
        + testInvalidSetAlternativeToItself()
        + testAddDepedency_RemoveDepedency()
        + testIllegalAddItself()
        + testIllegalRemoveDependency()
        + testIllegalSetAlternativeRecursive1()
        + testIllegalSetAlternativeRecursive2()
        + testIllegalSetAlternativeRecursive3()
        + testIllegalAddDependencyRecursive1()
        + testIllegalAddDependencyRecursive2()
    }
  }
  

  package test {
    class TimespanTest {
        ~ start : LocalDateTime
        ~ end : LocalDateTime
        + setUp()
        + testTimeSpan_legalCase()
        + testTimeSpan_illegalCase()
        + testCanHaveAsEndTime_legalCase()
        + testCanHaveAsEndTime_illegalCase()
    }
  }
  

  package test {
    class UserInterfaceTest {
    }
  }
  

  package test {
    class UserManagerTest {
        + setUp()
        + testCreateDeveloper()
        + testCreateProjectManager()
        + testLogin_illegalName()
        + testLogin_illegalPassword()
    }
  }
  

  package test {
    class XmlObjectTest {
        {static} - object : XmlObject
        + setUp()
        + tearDown()
        - deleteFile()
        + import_export()
    }
  }
  

  ClockTest o-- Clock : clock
  ControllerTest o-- Clock : clock
  ControllerTest o-- ProjectOrganizer : projectOrganizer
  ControllerTest o-- UserManager : userManager
  DeveloperTest o-- Developer : d
  ProjectManagerTest o-- ProjectManager : pm
  ProjectTest o-- Project : p
  ProjectTest o-- User : u
  TimespanTest o-- TimeSpan : timespan
  UserManagerTest o-- UserManager : u


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
