@startuml

title __PROJECTJJA's Class Diagram__\n

  package taskman {
    package taskman.backend {
      package taskman.backend.constraint {
        enum AmountComparator {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.constraint {
        class AndConstraint {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.time {
        class AvailabilityPeriod {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.wrappers {
        interface AvailabilityPeriodWrapper {
        }
      }
    }
  }
  

  package taskman {
    package taskman.frontend {
      package taskman.frontend.sections {
        class Cancel {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.time {
        class Clock {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.constraint {
        class Constraint {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.constraint {
        interface ConstraintComponent {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      class Controller {
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.user {
        class Developer {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.resource {
        class DeveloperResource {
        }
      }
    }
  }
  

  package taskman {
    package taskman.frontend {
      package taskman.frontend.sections {
        class FormSection {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.constraint {
        class IfThenConstraint {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.importexport {
        class ImportExportException {
        }
      }
    }
  }
  

  package taskman {
    class Initiator {
    }
  }
  

  package taskman {
    package taskman.frontend {
      package taskman.frontend.sections {
        class MenuSection {
        }
      }
    }
  }
  

  package taskman {
    package taskman.frontend {
      interface MethodCall {
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.constraint {
        class NotConstraint {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.user {
        class OperationNotPermittedException {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.constraint {
        class OrConstraint {
        }
      }
    }
  }
  

  package taskman {
    class Pair {
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.resource {
        class Plan {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.project {
        class Project {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.user {
        class ProjectManager {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.project {
        class ProjectOrganizer {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.wrappers {
        interface ProjectWrapper {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.resource {
        class Reservation {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.resource {
        class Resource {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.resource {
        class ResourceManager {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.resource {
        class ResourceType {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.wrappers {
        interface ResourceTypeWrapper {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.wrappers {
        interface ResourceWrapper {
        }
      }
    }
  }
  

  package taskman {
    package taskman.frontend {
      package taskman.frontend.sections {
        abstract class Section {
        }
      }
    }
  }
  

  package taskman {
    package taskman.frontend {
      package taskman.frontend.sections {
        class SelectionSection {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.simulation {
        class SimulationManager {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.task {
        class Task {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.task {
        abstract class TaskState {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.task {
        class TaskStateExecuting {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.task {
        class TaskStateFailed {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.task {
        class TaskStateFinished {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.task {
        class TaskStatePlanned {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.task {
        class TaskStateUnavailable {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.wrappers {
        interface TaskWrapper {
        }
      }
    }
  }
  

  package taskman {
    package taskman.frontend {
      package taskman.frontend.sections {
        class TextSection {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.time {
        class TimeParser {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.time {
        class TimeSpan {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.wrappers {
        interface TimeSpanWrapper {
        }
      }
    }
  }
  

  package taskman {
    package taskman.frontend {
      package taskman.frontend.sections {
        class TitleSection {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.user {
        abstract class User {
        }
      }
    }
  }
  

  package taskman {
    package taskman.frontend {
      class UserInterface {
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.user {
        class UserManager {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.wrappers {
        interface UserWrapper {
        }
      }
    }
  }
  

  package taskman {
    package taskman.backend {
      package taskman.backend.importexport {
        class XmlObject {
        }
      }
    }
  }
  

  AndConstraint -up-|> ConstraintComponent
  AndConstraint o-- ConstraintComponent : constraint1
  AndConstraint o-- ConstraintComponent : constraint2
  AvailabilityPeriod -up-|> AvailabilityPeriodWrapper
  Constraint -up-|> ConstraintComponent
  Constraint o-- ResourceType : resourceType
  Constraint o-- AmountComparator : amountComparator
  Controller o-- Clock : clock
  Controller o-- UserManager : userManager
  Controller o-- ProjectOrganizer : projectOrganizer
  Controller o-- ResourceManager : resourceManager
  Controller o-- SimulationManager : simulationManager
  Developer -up-|> User
  DeveloperResource -up-|> Resource
  DeveloperResource o-- AvailabilityPeriod : breakTime
  DeveloperResource o-- Developer : developer
  FormSection -up-|> Section
  IfThenConstraint -up-|> ConstraintComponent
  IfThenConstraint o-- ConstraintComponent : ifConstraint
  IfThenConstraint o-- ConstraintComponent : thenConstraint
  MenuSection -up-|> Section
  NotConstraint -up-|> ConstraintComponent
  NotConstraint o-- ConstraintComponent : constraint
  OrConstraint -up-|> ConstraintComponent
  OrConstraint o-- ConstraintComponent : constraint1
  OrConstraint o-- ConstraintComponent : constraint2
  Pair o-- First : first
  Pair o-- Second : second
  Plan o-- Task : task
  Project -up-|> ProjectWrapper
  ProjectManager -up-|> User
  Reservation o-- Resource : resource
  Reservation o-- TimeSpan : timeSpan
  Resource -up-|> ResourceWrapper
  Resource o-- ResourceType : type
  ResourceType -up-|> ResourceTypeWrapper
  SelectionSection -up-|> Section
  Task -up-|> TaskWrapper
  Task o-- TimeSpan : timeSpan
  Task o-- TaskState : state
  Task o-- Task : alternative
  Task o-- Plan : plan
  TaskStateExecuting -up-|> TaskState
  TaskStateFailed -up-|> TaskState
  TaskStateFinished -up-|> TaskState
  TaskStatePlanned -up-|> TaskState
  TaskStateUnavailable -up-|> TaskState
  TextSection -up-|> Section
  TimeSpan -up-|> TimeSpanWrapper
  TitleSection -up-|> Section
  TitleSection o-- TextSection : textSection
  User -up-|> UserWrapper
  UserInterface o-- Controller : controller
  UserManager o-- User : currentUser
  XmlObject o-- ResourceManager : resourceManager
  XmlObject o-- UserManager : userManager
  XmlObject o-- ProjectOrganizer : projectOrganizer
  XmlObject o-- Clock : clock


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
